### ISSUE TITLE
Training with multiprocessing for multi-gpu training.

### ISSUE THREAD

**Issue by MishallSwain** [xuannianz/EfficientDet#197]
**Versions:**
TF-GPU - 1.15 
Keras - 2.2.5(as needed in requirements.txt)
Code - Latest pull of the repo and no changes have been made

I have been trying to train EfficientDet on 8*K80 GPUS. But the training always gets stuck. Training seems to work for a single GPU with multiprocessing as false. I would like to use multi-gpu training with multiprocessing in order to train as fast as possible.

I have attached the commands and outputs for 3 cases.

**Command 1:**
python3 train.py --snapshot imagenet --phi 2 --gpu 0,1,2,3,4,5,6,7 --batch-size 16 --epochs 10 --multiprocessing --workers 16 --max-queue-size 10 --no-evaluation --weighted-bifpn --snapshot-path /home/ubuntu/ckpt/ csv ./train.csv ./class.csv

**Output 1:**
Epoch 1/10

**[Gets stuck, when interrupted prints]**

^CTraceback (most recent call last):
  File "train.py", line 366, in <module>
    main()
  File "train.py", line 361, in main
    max_queue_size=args.max_queue_size
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 783, in get
    inputs = self.queue.get(block=True).get()
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/eff/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

**Command 2:**
python3 train.py --snapshot imagenet --phi 2 --gpu 0 --batch-size 2 --epochs 10 --multiprocessing --workers 2 --max-queue-size 10 --no-evaluation --weighted-bifpn --snapshot-path /home/ubuntu/ckpt/ csv ./train.csv ./class.csv
**Output 2 same as Output 1**

**Command 3:**
python3 train.py --snapshot imagenet --phi 2 --gpu 0 --batch-size 2 --epochs 10 --no-evaluation --weighted-bifpn --snapshot-path /home/ubuntu/ckpt/ csv ./train.csv ./class.csv
**Output 3:**
Epoch 1/10
2020-07-27 13:00:38.954786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-27 13:00:39.891977: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-07-27 13:00:44.506551: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
2020-07-27 13:00:44.533709: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.0
    1/10000 [..............................] <Training gets completed but takes too much time>

**Comment by AutumnZ-94** [comment]
Multi gpu and large max queue size, without multiprocessing and 1 workers works for me, seems thats the fastest it could be.

**Comment by sanjaydeo96** [comment]
What was the GPU type u trained on,@AutumnZ-94? Can u elaborate more on what setup u did for that Multi-GPU training?

**Comment by AutumnZ-94** [comment]
> What was the GPU type u trained on,@AutumnZ-94? Can u elaborate more on what setup u did for that Multi-GPU training?

I used 4 Tesla K40m for training, and use a `with tf.device('/cpu:0'):"`to warp the model build part.
However the` point is `--multiprocessing `function stuck, even Multi-GPU loaded data, but generator data feed speed is slow. 

So that it is not fast much than single GPU.

BTW comparing from the keras-retinanet repo.
